server:
  port: 8082
spring:
  application:
    name: dubbo-cunsumer
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 121.36.136.81:8848

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://loaclhost
  cloud:
    subscribed-services: dubbo-provide
